const API_URL="https://countriesnow.space/api/v0.1/countries/info?returns=currency,flag,unicodeFlag,dialCode";
const countriesContainer=document.getElementById("countriesContainer"),searchInput=document.getElementById("searchInput"),regionFilter=document.getElementById("regionFilter"),status=document.getElementById("status"),countryModal=document.getElementById("countryModal"),modalInformation=document.getElementById("modalInformation"),closeModal=document.getElementById("closeModal"),themeButton=document.getElementById("themeButton");
let countries=[];
async function getCountries(){status.innerHTML='<span class="loader"></span> Consultando países...';try{const response=await fetch(API_URL);if(!response.ok)throw new Error(`Error HTTP: ${response.status}`);const result=await response.json();if(result.error)throw new Error("La API no pudo entregar los datos.");countries=result.data||[];countries.sort((a,b)=>a.name.localeCompare(b.name));displayCountries(countries)}catch(error){console.error("Error al consultar la API:",error);status.textContent="No fue posible consultar la API. Intenta nuevamente."}}
function displayCountries(countryList){countriesContainer.innerHTML="";if(countryList.length===0){status.textContent="No se encontraron países.";return}status.textContent=countryList.length===1?"1 país encontrado":`${countryList.length} países encontrados`;countryList.forEach(country=>{const card=document.createElement("article");card.classList.add("country-card");const flag=country.flag||"https://placehold.co/400x250?text=Sin+bandera",currency=country.currency||"No disponible",dialCode=country.dialCode||"No disponible";card.innerHTML=`<img src="${flag}" alt="Bandera de ${country.name}" loading="lazy"><div class="country-info"><h2>${country.name}</h2><p>🪙 <strong>Moneda:</strong> ${currency}</p><p>☎️ <strong>Indicativo:</strong> ${dialCode}</p><div class="card-action"><span>Ver detalles</span><span class="card-arrow">→</span></div></div>`;card.addEventListener("click",()=>showCountryDetails(country));countriesContainer.appendChild(card)})}
function filterCountries(){const search=searchInput.value.toLowerCase().trim();let filteredCountries=countries.filter(country=>country.name.toLowerCase().includes(search));const order=regionFilter.value;if(order==="AZ")filteredCountries.sort((a,b)=>a.name.localeCompare(b.name));else if(order==="ZA")filteredCountries.sort((a,b)=>b.name.localeCompare(a.name));displayCountries(filteredCountries)}
function showCountryDetails(country){const flag=country.flag||"https://placehold.co/600x350?text=Sin+bandera",currency=country.currency||"No disponible",dialCode=country.dialCode||"No disponible";modalInformation.innerHTML=`<div class="modal-country"><div class="modal-flag-container"><img src="${flag}" alt="Bandera de ${country.name}"></div><div class="modal-title"><div class="modal-country-icon">🌎</div><div><span class="modal-label">Información del país</span><h2>${country.name}</h2></div></div><div class="details-grid"><div class="detail-card"><div class="detail-icon">🪙</div><div><span>Moneda</span><strong>${currency}</strong></div></div><div class="detail-card"><div class="detail-icon">☎️</div><div><span>Indicativo telefónico</span><strong>${dialCode}</strong></div></div><div class="detail-card"><div class="detail-icon">📍</div><div><span>País consultado</span><strong>${country.name}</strong></div></div><div class="detail-card"><div class="detail-icon">🌐</div><div><span>Fuente de información</span><strong>CountriesNow API</strong></div></div></div><div class="api-note"><span>✓</span><span>Información obtenida mediante una consulta a una API remota.</span></div></div>`;countryModal.classList.remove("hidden")}
function closeCountryModal(){countryModal.classList.add("hidden")}
closeModal.addEventListener("click",closeCountryModal);countryModal.addEventListener("click",event=>{if(event.target===countryModal)closeCountryModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!countryModal.classList.contains("hidden"))closeCountryModal()});searchInput.addEventListener("input",filterCountries);regionFilter.addEventListener("change",filterCountries);
themeButton.addEventListener("click",()=>{document.body.classList.toggle("dark-mode");const darkMode=document.body.classList.contains("dark-mode");themeButton.innerHTML=darkMode?"☀️ <span>Modo claro</span>":"🌙 <span>Modo oscuro</span>"});
getCountries();